# docker-compose.yml

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpass
    # command: --server-id=1 --log-bin=mysql-bin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  maxwell:
    image: zendesk/maxwell
    container_name: maxwell_cdc
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MAXWELL_USER=student_user
      - MAXWELL_PASSWORD=student_pass
      - MAXWELL_HOST=db
      - MAXWELL_DATABASE=student_db
    # command: bin/maxwell --user=student_user --password=student_pass --host=db --output=stdout
    command: bin/maxwell --user=student_user --password=student_pass --host=db --producer=stdout

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

  presto:
    image: starburstdata/presto
    container_name: presto_engine
    ports:
      - "8080:8080"
    volumes:
      - ./docker/presto/catalog:/etc/presto/catalog
    depends_on:
      db:
        condition: service_healthy


volumes:
  mysql_data:
